## NUMPY ARRAY BASIC

In [9]:
import numpy as a

In [5]:
list1 = [1,2,3,4,5]

In [10]:
numpy_array = a.array(list1)

In [11]:
numpy_array

array([1, 2, 3, 4, 5])

In [16]:
numpy_array[0]

1

In [17]:
numpy_array[0:3]

array([1, 2, 3])

In [18]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [19]:
np_matrix = a.array(matrix)

In [21]:
np_matrix[1][1]

5

## NUMPY METHOD

In [22]:
my_np =  a.arange(1,10,2)

In [23]:
my_np

array([1, 3, 5, 7, 9])

In [24]:
np_matrix.shape

(2, 3)

In [25]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6]])